//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CnBlog
    {
        public int Id { get; set; }
        public string ArticleId { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Published { get; set; }
        public string Updated { get; set; }
        public string Link { get; set; }
        public string StaticLink { get; set; }
    }
}
